// 43099/frontend/src/pages/users/UserList.tsx
import { useState, useEffect } from 'react'
import { Table, Tag, Select, message, Card, Modal, Form, Input, Button } from 'antd'
import { EditOutlined } from '@ant-design/icons'
import { userApi } from '@/api'
import type { User } from '@/types'
import dayjs from 'dayjs'

const UserList = () => {
  const [users, setUsers] = useState<User[]>([])
  const [loading, setLoading] = useState(false)
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(10)
  const [editModalVisible, setEditModalVisible] = useState(false)
  const [editingUser, setEditingUser] = useState<User | null>(null)
  const [form] = Form.useForm()

  useEffect(() => {
    loadUsers()
  }, [page, pageSize])

  const loadUsers = async () => {
    setLoading(true)
    try {
      const data: any = await userApi.list({ page, page_size: pageSize })
      setUsers(data.list)
      setTotal(data.total)
    } catch (error: any) {
      message.error(error.message || '加载失败')
    } finally {
      setLoading(false)
    }
  }

  const handleEditRole = (user: User) => {
    setEditingUser(user)
    form.setFieldsValue({ role: user.role })
    setEditModalVisible(true)
  }

  const handleSubmitRole = async (values: any) => {
    if (!editingUser) return
    try {
      await userApi.updateRole(editingUser.id, values.role)
      message.success('角色更新成功')
      setEditModalVisible(false)
      loadUsers()
    } catch (error: any) {
      message.error(error.message || '更新失败')
    }
  }

  const getRoleTag = (role: string) => {
    const map: Record<string, { text: string; color: string }> = {
      user: { text: '普通用户', color: 'blue' },
      admin: { text: '管理员', color: 'orange' },
      super_admin: { text: '超级管理员', color: 'red' },
    }
    const info = map[role] || { text: role, color: 'default' }
    return <Tag color={info.color}>{info.text}</Tag>
  }

  const getStatusTag = (status: string) => {
    const color = status === 'active' ? 'green' : 'red'
    const text = status === 'active' ? '正常' : '禁用'
    return <Tag color={color}>{text}</Tag>
  }

  const columns = [
    {
      title: 'ID',
      dataIndex: 'id',
      key: 'id',
      width: 60,
    },
    {
      title: '用户名',
      dataIndex: 'username',
      key: 'username',
    },
    {
      title: '邮箱',
      dataIndex: 'email',
      key: 'email',
    },
    {
      title: '真实姓名',
      dataIndex: 'real_name',
      key: 'real_name',
    },
    {
      title: '电话',
      dataIndex: 'phone',
      key: 'phone',
    },
    {
      title: '角色',
      dataIndex: 'role',
      key: 'role',
      render: getRoleTag,
    },
    {
      title: '邮箱验证',
      dataIndex: 'email_verified',
      key: 'email_verified',
      render: (verified: boolean) => (
        <Tag color={verified ? 'green' : 'orange'}>
          {verified ? '已验证' : '未验证'}
        </Tag>
      ),
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      render: getStatusTag,
    },
    {
      title: '注册时间',
      dataIndex: 'created_at',
      key: 'created_at',
      render: (val: string) => dayjs(val).format('YYYY-MM-DD HH:mm'),
    },
    {
      title: '操作',
      key: 'action',
      render: (_: any, record: User) => (
        <Button type="link" icon={<EditOutlined />} onClick={() => handleEditRole(record)}>
          修改角色
        </Button>
      ),
    },
  ]

  return (
    <Card title="用户管理">
      <Table
        columns={columns}
        dataSource={users}
        rowKey="id"
        loading={loading}
        pagination={{
          current: page,
          pageSize,
          total,
          onChange: (p, ps) => {
            setPage(p)
            setPageSize(ps)
          },
        }}
      />

      <Modal
        title="修改用户角色"
        open={editModalVisible}
        onCancel={() => setEditModalVisible(false)}
        footer={null}
      >
        <Form form={form} layout="vertical" onFinish={handleSubmitRole}>
          <Form.Item label="用户">
            <Input value={editingUser?.username} disabled />
          </Form.Item>
          <Form.Item
            name="role"
            label="角色"
            rules={[{ required: true, message: '请选择角色' }]}
          >
            <Select placeholder="请选择角色">
              <Select.Option value="user">普通用户</Select.Option>
              <Select.Option value="admin">管理员</Select.Option>
              <Select.Option value="super_admin">超级管理员</Select.Option>
            </Select>
          </Form.Item>
          <Form.Item>
            <Button type="primary" htmlType="submit" block>
              保存
            </Button>
          </Form.Item>
        </Form>
      </Modal>
    </Card>
  )
}

export default UserList

// 43113/frontend/src/views/admin/UserList.vue
<template>
  <div class="user-list-page">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>用户管理</span>
          <el-input
            v-model="keyword"
            placeholder="搜索用户"
            style="width: 200px"
            clearable
            @keyup.enter="fetchUsers"
          >
            <template #prefix>
              <el-icon><Search /></el-icon>
            </template>
          </el-input>
        </div>
      </template>

      <el-table :data="users" style="width: 100%">
        <el-table-column label="用户" width="200">
          <template #default="{ row }">
            <div class="user-cell">
              <el-avatar :size="32" :src="row.avatar">
                {{ row.nickname?.charAt(0) || 'U' }}
              </el-avatar>
              <div class="user-info">
                <span class="username">{{ row.nickname || row.username }}</span>
                <el-tag v-if="row.isExpert" type="primary" size="small">专家</el-tag>
              </div>
            </div>
          </template>
        </el-table-column>
        <el-table-column prop="email" label="邮箱" />
        <el-table-column label="等级" width="100">
          <template #default="{ row }">
            Lv.{{ row.level }}
          </template>
        </el-table-column>
        <el-table-column prop="points" label="积分" width="100" />
        <el-table-column label="角色" width="100">
          <template #default="{ row }">
            <el-tag :type="row.role === 'admin' ? 'danger' : 'info'" size="small">
              {{ row.role === 'admin' ? '管理员' : '普通用户' }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="状态" width="100">
          <template #default="{ row }">
            <el-tag :type="getStatusType(row.status)" size="small">
              {{ getStatusName(row.status) }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="注册时间" width="180">
          <template #default="{ row }">
            {{ formatTime(row.createdAt) }}
          </template>
        </el-table-column>
        <el-table-column label="操作" width="200">
          <template #default="{ row }">
            <el-button
              v-if="row.status === 'active'"
              type="warning"
              size="small"
              @click="updateStatus(row.id, 'disabled')"
            >
              禁用
            </el-button>
            <el-button
              v-else
              type="success"
              size="small"
              @click="updateStatus(row.id, 'active')"
            >
              启用
            </el-button>
            <el-button
              v-if="row.status !== 'banned'"
              type="danger"
              size="small"
              @click="updateStatus(row.id, 'banned')"
            >
              封禁
            </el-button>
          </template>
        </el-table-column>
      </el-table>

      <el-pagination
        class="pagination"
        v-model:current-page="page"
        v-model:page-size="pageSize"
        :total="total"
        layout="prev, pager, next, total"
        @current-change="fetchUsers"
      />
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { userApi } from '@/api/user'
import type { User } from '@/types'
import dayjs from 'dayjs'

const users = ref<User[]>([])
const page = ref(1)
const pageSize = ref(10)
const total = ref(0)
const keyword = ref('')

const fetchUsers = async () => {
  try {
    const res = await userApi.getUserList({
      page: page.value,
      pageSize: pageSize.value,
      keyword: keyword.value
    })
    users.value = res.data?.list || []
    total.value = res.data?.total || 0
  } catch (e) {
    console.error(e)
  }
}

const updateStatus = async (id: number, status: string) => {
  try {
    await userApi.updateUserStatus(id, status)
    fetchUsers()
  } catch (e) {
    console.error(e)
  }
}

const getStatusType = (status: string) => {
  const map: Record<string, string> = {
    active: 'success',
    disabled: 'warning',
    banned: 'danger'
  }
  return map[status] || 'info'
}

const getStatusName = (status: string) => {
  const map: Record<string, string> = {
    active: '正常',
    disabled: '禁用',
    banned: '封禁'
  }
  return map[status] || status
}

const formatTime = (time: string) => {
  return dayjs(time).format('YYYY-MM-DD HH:mm:ss')
}

onMounted(() => {
  fetchUsers()
})
</script>

<style scoped lang="scss">
.user-list-page {
  .card-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .user-cell {
    display: flex;
    align-items: center;
    gap: 12px;

    .user-info {
      display: flex;
      flex-direction: column;
      gap: 4px;

      .username {
        font-weight: 500;
      }
    }
  }

  .pagination {
    justify-content: center;
    margin-top: 20px;
  }
}
</style>
