// 43127/frontend/src/views/Profile.vue
<template>
  <div class="profile">
    <div class="page-header">
      <h2 class="page-title">个人中心</h2>
    </div>

    <el-row :gutter="20">
      <el-col :span="8">
        <div class="card avatar-card">
          <el-avatar :size="120" :src="userStore.userInfo?.avatar">
            {{ userStore.userInfo?.realName?.charAt(0) || 'U' }}
          </el-avatar>
          <h2>{{ userStore.userInfo?.realName }}</h2>
          <p>{{ getRoleText(userStore.userInfo?.role) }}</p>
          <el-upload
            :show-file-list="false"
            :before-upload="beforeUpload"
            :http-request="handleAvatarUpload"
            accept="image/*"
          >
            <el-button type="primary" plain>更换头像</el-button>
          </el-upload>
        </div>
      </el-col>

      <el-col :span="16">
        <div class="card">
          <el-form
            ref="formRef"
            :model="form"
            :rules="rules"
            label-width="100px"
          >
            <el-form-item label="用户名">
              <el-input v-model="form.username" disabled />
            </el-form-item>
            <el-form-item label="真实姓名" prop="realName">
              <el-input v-model="form.realName" />
            </el-form-item>
            <el-form-item label="手机号" prop="phone">
              <el-input v-model="form.phone" />
            </el-form-item>
            <el-form-item label="邮箱" prop="email">
              <el-input v-model="form.email" />
            </el-form-item>
            <el-form-item>
              <el-button type="primary" :loading="loading" @click="handleSubmit">
                保存修改
              </el-button>
            </el-form-item>
          </el-form>
        </div>
      </el-col>
    </el-row>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { ElMessage, type FormInstance, type FormRules, type UploadProps } from 'element-plus'
import { useUserStore } from '@/store/user'
import { updateProfile } from '@/api/auth'
import { uploadImage } from '@/api/property'

const userStore = useUserStore()
const loading = ref(false)
const formRef = ref<FormInstance>()

const form = reactive({
  username: '',
  realName: '',
  phone: '',
  email: '',
  avatar: ''
})

const rules: FormRules = {
  realName: [{ required: true, message: '请输入真实姓名', trigger: 'blur' }],
  phone: [{ required: true, message: '请输入手机号', trigger: 'blur' }]
}

onMounted(() => {
  if (userStore.userInfo) {
    form.username = userStore.userInfo.username
    form.realName = userStore.userInfo.realName
    form.phone = userStore.userInfo.phone
    form.email = userStore.userInfo.email
    form.avatar = userStore.userInfo.avatar
  }
})

function getRoleText(role?: string) {
  switch (role) {
    case 'admin': return '管理员'
    case 'landlord': return '房东'
    case 'maintainer': return '维修人员'
    default: return '租户'
  }
}

const beforeUpload: UploadProps['beforeUpload'] = (file) => {
  const isImage = file.type.startsWith('image/')
  if (!isImage) {
    ElMessage.error('只能上传图片文件')
    return false
  }
  return true
}

async function handleAvatarUpload(options: any) {
  try {
    const res = await uploadImage(options.file)
    form.avatar = res.data.url
    await updateProfile({ avatar: form.avatar })
    ElMessage.success('头像更新成功')
    await userStore.fetchUserInfo()
  } catch (error) {
    console.error('Upload failed:', error)
  }
}

async function handleSubmit() {
  if (!formRef.value) return
  
  await formRef.value.validate(async (valid) => {
    if (valid) {
      loading.value = true
      try {
        await updateProfile({
          realName: form.realName,
          phone: form.phone,
          email: form.email
        })
        ElMessage.success('保存成功')
        await userStore.fetchUserInfo()
      } catch (error) {
        console.error('Submit failed:', error)
      } finally {
        loading.value = false
      }
    }
  })
}
</script>

<style scoped>
.profile {
  padding: 0;
}

.avatar-card {
  text-align: center;
  padding: 30px;
}

.avatar-card .el-avatar {
  margin-bottom: 15px;
}

.avatar-card h2 {
  margin: 10px 0;
  font-size: 20px;
}

.avatar-card p {
  color: #909399;
  margin-bottom: 20px;
}
</style>

// 43115/frontend/src/pages/Profile.tsx
import React, { useState, useEffect } from 'react'
import { Card, Form, Input, Button, Avatar, Upload, message, Row, Col } from 'antd'
import { UploadOutlined } from '@ant-design/icons'
import { authApi } from '@/services/auth'
import { useAppSelector, useAppDispatch } from '@/store/hooks'
import { setUserInfo } from '@/store'

const Profile: React.FC = () => {
  const { userInfo } = useAppSelector((state) => state.auth)
  const dispatch = useAppDispatch()
  const [form] = Form.useForm()
  const [loading, setLoading] = useState(false)
  const [passwordForm] = Form.useForm()
  const [changingPassword, setChangingPassword] = useState(false)

  useEffect(() => {
    if (userInfo) {
      form.setFieldsValue({
        nickname: userInfo.nickname,
        phone: userInfo.phone,
      })
    }
  }, [userInfo])

  const handleUpdateProfile = async () => {
    try {
      const values = await form.validateFields()
      setLoading(true)
      const res = await authApi.updateProfile(values)
      dispatch(setUserInfo(res))
      message.success('更新成功')
    } catch (error) {
      console.error(error)
    } finally {
      setLoading(false)
    }
  }

  const handleChangePassword = async () => {
    try {
      const values = await passwordForm.validateFields()
      if (values.new_password !== values.confirm_password) {
        message.error('两次输入的密码不一致')
        return
      }
      setChangingPassword(true)
      await authApi.changePassword(values)
      message.success('密码修改成功')
      passwordForm.resetFields()
    } catch (error) {
      console.error(error)
    } finally {
      setChangingPassword(false)
    }
  }

  return (
    <div>
      <div className="page-header">
        <h1 className="page-title">个人中心</h1>
      </div>

      <Row gutter={24}>
        <Col span={8}>
          <Card style={{ textAlign: 'center' }}>
            <Avatar size={100} src={userInfo?.avatar}>
              {userInfo?.nickname?.charAt(0)}
            </Avatar>
            <h2 style={{ marginTop: 16 }}>{userInfo?.nickname}</h2>
            <p style={{ color: '#999' }}>
              {userInfo?.role === 'customer' && '客户'}
              {userInfo?.role === 'service_provider' && '服务人员'}
              {userInfo?.role === 'admin' && '管理员'}
            </p>
            <Upload
              name="avatar"
              showUploadList={false}
              action="/api/upload/avatar"
              onChange={async (info) => {
                if (info.file.status === 'done') {
                  message.success('头像上传成功')
                  try {
                    const res = await authApi.getCurrentUser()
                    dispatch(setUserInfo(res))
                    localStorage.setItem('userInfo', JSON.stringify(res))
                  } catch (error) {
                    console.error(error)
                  }
                }
              }}
            >
              <Button icon={<UploadOutlined />}>更换头像</Button>
            </Upload>
          </Card>
        </Col>

        <Col span={16}>
          <Card title="基本信息" style={{ marginBottom: 24 }}>
            <Form form={form} layout="vertical">
              <Form.Item
                name="nickname"
                label="昵称"
                rules={[{ required: true, message: '请输入昵称' }]}
              >
                <Input placeholder="请输入昵称" />
              </Form.Item>
              <Form.Item name="phone" label="手机号">
                <Input disabled />
              </Form.Item>
              <Form.Item>
                <Button
                  type="primary"
                  loading={loading}
                  onClick={handleUpdateProfile}
                >
                  保存修改
                </Button>
              </Form.Item>
            </Form>
          </Card>

          <Card title="修改密码">
            <Form form={passwordForm} layout="vertical">
              <Form.Item
                name="old_password"
                label="当前密码"
                rules={[{ required: true, message: '请输入当前密码' }]}
              >
                <Input.Password placeholder="请输入当前密码" />
              </Form.Item>
              <Form.Item
                name="new_password"
                label="新密码"
                rules={[{ required: true, message: '请输入新密码' }]}
              >
                <Input.Password placeholder="请输入新密码" />
              </Form.Item>
              <Form.Item
                name="confirm_password"
                label="确认新密码"
                rules={[{ required: true, message: '请再次输入新密码' }]}
              >
                <Input.Password placeholder="请再次输入新密码" />
              </Form.Item>
              <Form.Item>
                <Button
                  type="primary"
                  loading={changingPassword}
                  onClick={handleChangePassword}
                >
                  修改密码
                </Button>
              </Form.Item>
            </Form>
          </Card>
        </Col>
      </Row>
    </div>
  )
}

export default Profile
