// 43177/frontend/src/views/admin/Categories.vue
<template>
  <div class="admin-categories-page">
    <div class="page-header">
      <h2 class="page-title">分类管理</h2>
      <el-button type="primary" @click="showCreateDialog = true">
        新增分类
      </el-button>
    </div>

    <el-card>
      <el-table :data="categories" style="width: 100%">
        <el-table-column prop="icon" label="图标" width="100">
          <template #default="{ row }">
            <span style="font-size: 24px;">{{ row.icon }}</span>
          </template>
        </el-table-column>
        <el-table-column prop="name" label="名称" width="150" />
        <el-table-column prop="code" label="编码" width="150" />
        <el-table-column prop="sort" label="排序" width="100" />
        <el-table-column label="状态" width="100">
          <template #default="{ row }">
            <el-tag :type="row.status ? 'success' : 'danger'">
              {{ row.status ? '正常' : '禁用' }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="150">
          <template #default="{ row }">
            <el-button size="small" @click="editCategory(row)">编辑</el-button>
            <el-button size="small" type="danger" @click="deleteCategory(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-dialog v-model="showCreateDialog" :title="editingCategory ? '编辑分类' : '新增分类'" width="400px">
      <el-form :model="categoryForm" label-width="80px">
        <el-form-item label="名称">
          <el-input v-model="categoryForm.name" />
        </el-form-item>
        <el-form-item label="编码">
          <el-input v-model="categoryForm.code" />
        </el-form-item>
        <el-form-item label="图标">
          <el-input v-model="categoryForm.icon" placeholder="输入emoji或图标URL" />
        </el-form-item>
        <el-form-item label="排序">
          <el-input-number v-model="categoryForm.sort" :min="0" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="showCreateDialog = false">取消</el-button>
        <el-button type="primary" @click="saveCategory" :loading="saving">保存</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { categoryApi } from '@/api/category'
import type { Category } from '@/types'

const categories = ref<Category[]>([])
const showCreateDialog = ref(false)
const editingCategory = ref<Category | null>(null)
const saving = ref(false)

const categoryForm = reactive({
  name: '',
  code: '',
  icon: '',
  sort: 0
})

onMounted(() => {
  loadCategories()
})

async function loadCategories() {
  try {
    const res = await categoryApi.getCategories()
    categories.value = res.data || []
  } catch (error) {
    console.error('Failed to load categories:', error)
  }
}

function editCategory(category: Category) {
  editingCategory.value = category
  categoryForm.name = category.name
  categoryForm.code = category.code
  categoryForm.icon = category.icon
  categoryForm.sort = category.sort
  showCreateDialog.value = true
}

async function saveCategory() {
  if (!categoryForm.name || !categoryForm.code) {
    ElMessage.error('请填写名称和编码')
    return
  }

  saving.value = true
  try {
    if (editingCategory.value) {
      await categoryApi.updateCategory(editingCategory.value.id, categoryForm)
    } else {
      await categoryApi.createCategory(categoryForm)
    }
    ElMessage.success('保存成功')
    showCreateDialog.value = false
    resetForm()
    loadCategories()
  } catch (error) {
    console.error('Failed to save category:', error)
  } finally {
    saving.value = false
  }
}

function resetForm() {
  editingCategory.value = null
  categoryForm.name = ''
  categoryForm.code = ''
  categoryForm.icon = ''
  categoryForm.sort = 0
}

async function deleteCategory(category: Category) {
  try {
    await ElMessageBox.confirm(`确定要删除分类"${category.name}"吗？`, '确认', { type: 'warning' })
    await categoryApi.deleteCategory(category.id)
    ElMessage.success('删除成功')
    loadCategories()
  } catch (error: any) {
    if (error !== 'cancel') {
      console.error('Failed to delete category:', error)
    }
  }
}
</script>

<style scoped>
.admin-categories-page {
  padding: 0;
}
</style>

// 43082/frontend/src/pages/Admin/Categories.tsx
import { useState, useEffect } from 'react'
import {
  Table, Button, Card, Typography, Tag, Space, Popconfirm,
  message, Modal, Form, Input, InputNumber
} from 'antd'
import { PlusOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons'
import { categoryAPI } from '@/api'
import { Category } from '@/types'

const { Title } = Typography

const AdminCategories = () => {
  const [categories, setCategories] = useState<Category[]>([])
  const [modalVisible, setModalVisible] = useState(false)
  const [editingCategory, setEditingCategory] = useState<Category | null>(null)
  const [form] = Form.useForm()

  useEffect(() => {
    loadCategories()
  }, [])

  const loadCategories = async () => {
    try {
      const res = await categoryAPI.list() as any
      setCategories(res.data)
    } catch (err) {
      console.error('加载分类失败', err)
    }
  }

  const handleAdd = () => {
    setEditingCategory(null)
    form.resetFields()
    setModalVisible(true)
  }

  const handleEdit = (category: Category) => {
    setEditingCategory(category)
    form.setFieldsValue(category)
    setModalVisible(true)
  }

  const handleDelete = async (id: number) => {
    try {
      await categoryAPI.delete(id)
      message.success('删除成功')
      loadCategories()
    } catch (err: any) {
      message.error(err.message || '删除失败')
    }
  }

  const handleSubmit = async (values: any) => {
    try {
      if (editingCategory) {
        await categoryAPI.update(editingCategory.id, values)
      } else {
        await categoryAPI.create(values)
      }
      message.success(editingCategory ? '更新成功' : '创建成功')
      setModalVisible(false)
      loadCategories()
    } catch (err: any) {
      message.error(err.message || '操作失败')
    }
  }

  const columns = [
    {
      title: 'ID',
      dataIndex: 'id',
      key: 'id',
      width: 80,
    },
    {
      title: '分类名称',
      dataIndex: 'name',
      key: 'name',
    },
    {
      title: '排序',
      dataIndex: 'sort',
      key: 'sort',
      width: 100,
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      width: 100,
      render: (status: string) => (
        <Tag color={status === 'active' ? 'green' : 'red'}>
          {status === 'active' ? '启用' : '禁用'}
        </Tag>
      ),
    },
    {
      title: '创建时间',
      dataIndex: 'createdAt',
      key: 'createdAt',
    },
    {
      title: '操作',
      key: 'action',
      width: 160,
      render: (_: any, record: Category) => (
        <Space>
          <Button
            size="small"
            icon={<EditOutlined />}
            onClick={() => handleEdit(record)}
          >
            编辑
          </Button>
          <Popconfirm title="确定删除该分类？" onConfirm={() => handleDelete(record.id)}>
            <Button size="small" danger icon={<DeleteOutlined />}>删除</Button>
          </Popconfirm>
        </Space>
      ),
    },
  ]

  return (
    <div>
      <div className="page-header">
        <Title level={3} style={{ margin: 0 }}>分类管理</Title>
        <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
          添加分类
        </Button>
      </div>

      <Card>
        <Table
          columns={columns}
          dataSource={categories}
          rowKey="id"
          pagination={false}
        />
      </Card>

      <Modal
        title={editingCategory ? '编辑分类' : '添加分类'}
        open={modalVisible}
        onCancel={() => setModalVisible(false)}
        footer={null}
      >
        <Form form={form} layout="vertical" onFinish={handleSubmit}>
          <Form.Item
            name="name"
            label="分类名称"
            rules={[{ required: true, message: '请输入分类名称' }]}
          >
            <Input placeholder="请输入分类名称" />
          </Form.Item>
          <Form.Item
            name="sort"
            label="排序"
            initialValue={0}
          >
            <InputNumber min={0} style={{ width: '100%' }} />
          </Form.Item>
          <Form.Item>
            <Button type="primary" htmlType="submit" style={{ width: '100%' }}>
              {editingCategory ? '更新' : '创建'}
            </Button>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  )
}

export default AdminCategories
