// 43116/frontend/src/views/admin/Users.vue
<template>
  <div>
    <div class="page-header">
      <h1 class="page-title">用户管理</h1>
    </div>

    <div class="search-bar">
      <el-input
        v-model="filters.keyword"
        placeholder="搜索用户名/邮箱/姓名"
        clearable
        style="width: 250px"
        @keyup.enter="loadUsers"
      >
        <template #prefix>
          <el-icon><Search /></el-icon>
        </template>
      </el-input>
      <el-button type="primary" @click="loadUsers">搜索</el-button>
    </div>

    <el-table :data="users" v-loading="loading" style="width: 100%">
      <el-table-column prop="id" label="ID" width="80" />
      <el-table-column prop="username" label="用户名" width="150" />
      <el-table-column prop="email" label="邮箱" width="200" />
      <el-table-column prop="phone" label="手机号" width="130" />
      <el-table-column prop="real_name" label="真实姓名" width="120" />
      <el-table-column label="认证状态" width="100">
        <template #default="{ row }">
          <el-tag :type="getAuthStatusType(row.auth_status)">
            {{ getAuthStatusText(row.auth_status) }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column label="账户状态" width="100">
        <template #default="{ row }">
          <el-tag :type="row.status === 'active' ? 'success' : 'danger'">
            {{ row.status === 'active' ? '正常' : '禁用' }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column label="注册时间" width="170">
        <template #default="{ row }">
          {{ formatDate(row.created_at) }}
        </template>
      </el-table-column>
      <el-table-column label="操作" width="200" fixed="right">
        <template #default="{ row }">
          <el-button
            v-if="row.auth_status === 'pending'"
            type="success"
            size="small"
            @click="handleAuth(row.id, 'active')"
          >
            通过认证
          </el-button>
          <el-button
            v-if="row.auth_status === 'pending'"
            type="danger"
            size="small"
            @click="handleAuth(row.id, 'rejected')"
          >
            拒绝
          </el-button>
          <el-button
            v-if="row.status === 'active'"
            type="warning"
            size="small"
            @click="handleStatus(row.id, 'disabled')"
          >
            禁用
          </el-button>
          <el-button
            v-else
            type="success"
            size="small"
            @click="handleStatus(row.id, 'active')"
          >
            启用
          </el-button>
        </template>
      </el-table-column>
    </el-table>

    <div style="text-align: center; margin-top: 20px;">
      <el-pagination
        v-model:current-page="pagination.page"
        v-model:page-size="pagination.pageSize"
        :total="pagination.total"
        layout="total, sizes, prev, pager, next, jumper"
        :page-sizes="[10, 20, 50]"
        @size-change="loadUsers"
        @current-change="loadUsers"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Search } from '@element-plus/icons-vue'
import dayjs from 'dayjs'
import { userApi } from '@/api'
import type { User } from '@/types'

const users = ref<User[]>([])
const loading = ref(false)

const filters = reactive({
  keyword: ''
})

const pagination = reactive({
  page: 1,
  pageSize: 10,
  total: 0
})

onMounted(() => {
  loadUsers()
})

const loadUsers = async () => {
  loading.value = true
  try {
    const res = await userApi.getUsers({
      page: pagination.page,
      page_size: pagination.pageSize,
      keyword: filters.keyword
    })
    users.value = res.data.items
    pagination.total = res.data.total
  } catch {
    // ignore
  } finally {
    loading.value = false
  }
}

const handleAuth = async (id: number, status: string) => {
  try {
    const action = status === 'active' ? '通过' : '拒绝'
    await ElMessageBox.confirm(`确定要${action}该用户的认证吗？`, '提示', {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning'
    })

    await userApi.updateAuthStatus(id, status)
    ElMessage.success('操作成功')
    loadUsers()
  } catch (err: any) {
    if (err !== 'cancel') {
      ElMessage.error(err.message || '操作失败')
    }
  }
}

const handleStatus = async (id: number, status: string) => {
  try {
    await userApi.updateUserStatus(id, status)
    ElMessage.success('操作成功')
    loadUsers()
  } catch (err: any) {
    ElMessage.error(err.message || '操作失败')
  }
}

const formatDate = (date: string) => {
  return dayjs(date).format('YYYY-MM-DD HH:mm')
}

const getAuthStatusType = (status: string) => {
  const map: Record<string, string> = {
    pending: 'warning',
    active: 'success',
    disabled: 'info',
    rejected: 'danger'
  }
  return map[status] || 'info'
}

const getAuthStatusText = (status: string) => {
  const map: Record<string, string> = {
    pending: '待审核',
    active: '已认证',
    disabled: '已禁用',
    rejected: '已拒绝'
  }
  return map[status] || status
}
</script>

// 43082/frontend/src/pages/Admin/Users.tsx
import { useState, useEffect } from 'react'
import {
  Table, Button, Card, Typography, Tag, Space, Pagination,
  message, Input, Select
} from 'antd'
import { SearchOutlined } from '@ant-design/icons'
import { adminAPI } from '@/api'
import { User } from '@/types'

const { Title } = Typography
const { Option } = Select

const AdminUsers = () => {
  const [users, setUsers] = useState<User[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [pageSize] = useState(10)
  const [keyword, setKeyword] = useState('')
  const [role, setRole] = useState<string>('')

  useEffect(() => {
    loadUsers()
  }, [page, keyword, role])

  const loadUsers = async () => {
    try {
      const params: any = { page, pageSize }
      if (keyword) params.keyword = keyword
      if (role) params.role = role
      const res = await adminAPI.getUsers(params)
      setUsers(res.data.data)
      setTotal(res.data.pagination.total)
    } catch (err) {
      console.error('加载用户失败', err)
    }
  }

  const getRoleTag = (role: string) => {
    const roleMap: Record<string, { color: string; text: string }> = {
      buyer: { color: 'blue', text: '买家' },
      seller: { color: 'green', text: '商家' },
      admin: { color: 'gold', text: '管理员' },
    }
    const info = roleMap[role] || { color: 'default', text: role }
    return <Tag color={info.color}>{info.text}</Tag>
  }

  const getStatusTag = (status: string) => {
    const statusMap: Record<string, { color: string; text: string }> = {
      active: { color: 'green', text: '正常' },
      banned: { color: 'red', text: '已封禁' },
    }
    const info = statusMap[status] || { color: 'default', text: status }
    return <Tag color={info.color}>{info.text}</Tag>
  }

  // 后端暂未提供更新用户状态接口，功能已禁用
  // const handleBanUser = async (id: number, status: string) => {
  //   try {
  //     await adminAPI.updateUserStatus(id, { status })
  //     message.success(status === 'banned' ? '已封禁' : '已解封')
  //     loadUsers()
  //   } catch (err: any) {
  //     message.error(err.message || '操作失败')
  //   }
  // }

  const columns = [
    {
      title: 'ID',
      dataIndex: 'id',
      key: 'id',
      width: 80,
    },
    {
      title: '用户名',
      dataIndex: 'username',
      key: 'username',
    },
    {
      title: '昵称',
      dataIndex: 'nickname',
      key: 'nickname',
    },
    {
      title: '邮箱',
      dataIndex: 'email',
      key: 'email',
    },
    {
      title: '手机号',
      dataIndex: 'phone',
      key: 'phone',
    },
    {
      title: '角色',
      dataIndex: 'role',
      key: 'role',
      render: (role: string) => getRoleTag(role),
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      render: (status: string) => getStatusTag(status),
    },
    {
      title: '注册时间',
      dataIndex: 'createdAt',
      key: 'createdAt',
    },
    // 后端暂未提供更新用户状态接口，操作列已禁用
    // {
    //   title: '操作',
    //   key: 'action',
    //   width: 150,
    //   render: (_: any, record: User) => (
    //     <Space>
    //       {record.status === 'active' ? (
    //         <Button
    //           danger
    //           size="small"
    //           onClick={() => handleBanUser(record.id, 'banned')}
    //         >
    //           封禁
    //         </Button>
    //       ) : (
    //         <Button
    //           type="primary"
    //           size="small"
    //           onClick={() => handleBanUser(record.id, 'active')}
    //         >
    //           解封
    //         </Button>
    //       )}
    //     </Space>
    //   ),
    // },
  ]

  return (
    <div>
      <Title level={3}>用户管理</Title>

      <Card>
        <div style={{ display: 'flex', gap: 16, marginBottom: 16 }}>
          <Input.Search
            placeholder="搜索用户名/昵称..."
            value={keyword}
            onChange={(e) => setKeyword(e.target.value)}
            onSearch={() => setPage(1)}
            style={{ width: 300 }}
            allowClear
          />
          <Select
            placeholder="选择角色"
            allowClear
            style={{ width: 150 }}
            value={role}
            onChange={(val) => { setRole(val); setPage(1) }}
          >
            <Option value="buyer">买家</Option>
            <Option value="seller">商家</Option>
            <Option value="admin">管理员</Option>
          </Select>
        </div>

        <Table
          columns={columns}
          dataSource={users}
          rowKey="id"
          pagination={false}
        />

        <div style={{ textAlign: 'center', marginTop: 24 }}>
          <Pagination
            current={page}
            pageSize={pageSize}
            total={total}
            onChange={setPage}
          />
        </div>
      </Card>
    </div>
  )
}

export default AdminUsers
