// 43177/frontend/src/views/admin/Users.vue
<template>
  <div class="admin-users-page">
    <div class="page-header">
      <h2 class="page-title">用户管理</h2>
    </div>

    <el-card>
      <div class="filter-bar">
        <el-select v-model="roleFilter" placeholder="选择角色" clearable style="width: 150px;" @change="loadUsers">
          <el-option label="客户" value="customer" />
          <el-option label="技师" value="technician" />
          <el-option label="管理员" value="admin" />
        </el-select>
        <el-select v-model="statusFilter" placeholder="选择状态" clearable style="width: 150px;" @change="loadUsers">
          <el-option label="正常" value="active" />
          <el-option label="禁用" value="disabled" />
          <el-option label="待审核" value="pending" />
        </el-select>
      </div>

      <el-table :data="users" style="width: 100%">
        <el-table-column prop="id" label="ID" width="80" />
        <el-table-column prop="username" label="用户名" width="150" />
        <el-table-column prop="real_name" label="真实姓名" width="150" />
        <el-table-column prop="phone" label="手机号" width="150" />
        <el-table-column prop="email" label="邮箱" width="200" />
        <el-table-column prop="role" label="角色" width="100">
          <template #default="{ row }">
            <el-tag :type="getRoleType(row.role)">{{ getRoleText(row.role) }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="status" label="状态" width="100">
          <template #default="{ row }">
            <el-tag :type="getStatusType(row.status)">{{ getStatusText(row.status) }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="balance" label="余额" width="120">
          <template #default="{ row }">¥{{ row.balance }}</template>
        </el-table-column>
        <el-table-column prop="created_at" label="注册时间" width="180">
          <template #default="{ row }">{{ formatTime(row.created_at) }}</template>
        </el-table-column>
        <el-table-column label="操作" width="150">
          <template #default="{ row }">
            <el-button size="small" @click="viewUser(row)">查看</el-button>
            <el-button
              size="small"
              :type="row.status === 'active' ? 'danger' : 'success'"
              @click="toggleStatus(row)"
            >
              {{ row.status === 'active' ? '禁用' : '启用' }}
            </el-button>
          </template>
        </el-table-column>
      </el-table>

      <div v-if="total > pageSize" class="pagination">
        <el-pagination
          v-model:current-page="currentPage"
          :page-size="pageSize"
          :total="total"
          layout="prev, pager, next"
          @current-change="loadUsers"
        />
      </div>
    </el-card>

    <el-dialog v-model="showDetailDialog" title="用户详情" width="600px">
      <el-descriptions :column="2" border v-if="selectedUser">
        <el-descriptions-item label="ID">{{ selectedUser.id }}</el-descriptions-item>
        <el-descriptions-item label="用户名">{{ selectedUser.username }}</el-descriptions-item>
        <el-descriptions-item label="真实姓名">{{ selectedUser.real_name || '-' }}</el-descriptions-item>
        <el-descriptions-item label="手机号">{{ selectedUser.phone }}</el-descriptions-item>
        <el-descriptions-item label="邮箱">{{ selectedUser.email || '-' }}</el-descriptions-item>
        <el-descriptions-item label="角色">
          <el-tag :type="getRoleType(selectedUser.role)">{{ getRoleText(selectedUser.role) }}</el-tag>
        </el-descriptions-item>
        <el-descriptions-item label="状态">
          <el-tag :type="getStatusType(selectedUser.status)">{{ getStatusText(selectedUser.status) }}</el-tag>
        </el-descriptions-item>
        <el-descriptions-item label="余额">¥{{ selectedUser.balance }}</el-descriptions-item>
        <el-descriptions-item label="地址">{{ selectedUser.address || '-' }}</el-descriptions-item>
        <el-descriptions-item label="注册时间">{{ formatTime(selectedUser.created_at) }}</el-descriptions-item>
      </el-descriptions>

      <el-card v-if="selectedUser?.technician_profile" class="mt-20">
        <template #header>技师信息</template>
        <el-descriptions :column="2" border>
          <el-descriptions-item label="专业">
            {{ selectedUser.technician_profile.specialty || '-' }}
          </el-descriptions-item>
          <el-descriptions-item label="评分">
            {{ selectedUser.technician_profile.rating }}
          </el-descriptions-item>
          <el-descriptions-item label="完成订单">
            {{ selectedUser.technician_profile.completed_orders }}
          </el-descriptions-item>
          <el-descriptions-item label="认证状态">
            <el-tag :type="selectedUser.technician_profile.is_verified ? 'success' : 'warning'">
              {{ selectedUser.technician_profile.is_verified ? '已认证' : '未认证' }}
            </el-tag>
          </el-descriptions-item>
        </el-descriptions>
      </el-card>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { adminApi } from '@/api/admin'
import type { User } from '@/types'
import dayjs from 'dayjs'

const users = ref<User[]>([])
const currentPage = ref(1)
const pageSize = ref(10)
const total = ref(0)
const roleFilter = ref('')
const statusFilter = ref('')
const showDetailDialog = ref(false)
const selectedUser = ref<any>(null)

onMounted(() => {
  loadUsers()
})

async function loadUsers() {
  try {
    const res = await adminApi.getUsers({
      page: currentPage.value,
      page_size: pageSize.value,
      role: roleFilter.value || undefined,
      status: statusFilter.value || undefined
    })
    users.value = res.data?.list || []
    total.value = res.data?.total || 0
  } catch (error) {
    console.error('Failed to load users:', error)
  }
}

function getRoleType(role: string): string {
  const typeMap: Record<string, string> = {
    customer: 'info',
    technician: 'success',
    admin: 'warning'
  }
  return typeMap[role] || 'info'
}

function getRoleText(role: string): string {
  const textMap: Record<string, string> = {
    customer: '客户',
    technician: '技师',
    admin: '管理员'
  }
  return textMap[role] || role
}

function getStatusType(status: string): string {
  const typeMap: Record<string, string> = {
    active: 'success',
    disabled: 'danger',
    pending: 'warning'
  }
  return typeMap[status] || 'info'
}

function getStatusText(status: string): string {
  const textMap: Record<string, string> = {
    active: '正常',
    disabled: '禁用',
    pending: '待审核'
  }
  return textMap[status] || status
}

function formatTime(time: string): string {
  return dayjs(time).format('YYYY-MM-DD HH:mm')
}

async function viewUser(user: User) {
  try {
    const res = await adminApi.getUserDetail(user.id)
    selectedUser.value = res.data
    showDetailDialog.value = true
  } catch (error) {
    console.error('Failed to load user detail:', error)
  }
}

async function toggleStatus(user: User) {
  const newStatus = user.status === 'active' ? 'disabled' : 'active'
  try {
    await ElMessageBox.confirm(
      `确定要${newStatus === 'active' ? '启用' : '禁用'}该用户吗？`,
      '确认',
      { type: 'warning' }
    )
    await adminApi.updateUserStatus(user.id, { status: newStatus })
    ElMessage.success('操作成功')
    loadUsers()
  } catch (error: any) {
    if (error !== 'cancel') {
      console.error('Failed to update status:', error)
    }
  }
}
</script>

<style scoped>
.admin-users-page {
  padding: 0;
}

.filter-bar {
  display: flex;
  gap: 15px;
  margin-bottom: 20px;
}

.pagination {
  display: flex;
  justify-content: center;
  margin-top: 20px;
}

.mt-20 {
  margin-top: 20px;
}
</style>

// 43082/frontend/src/pages/Admin/Users.tsx
import { useState, useEffect } from 'react'
import {
  Table, Button, Card, Typography, Tag, Space, Pagination,
  message, Input, Select
} from 'antd'
import { SearchOutlined } from '@ant-design/icons'
import { adminAPI } from '@/api'
import { User } from '@/types'

const { Title } = Typography
const { Option } = Select

const AdminUsers = () => {
  const [users, setUsers] = useState<User[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [pageSize] = useState(10)
  const [keyword, setKeyword] = useState('')
  const [role, setRole] = useState<string>('')

  useEffect(() => {
    loadUsers()
  }, [page, keyword, role])

  const loadUsers = async () => {
    try {
      const params: any = { page, pageSize }
      if (keyword) params.keyword = keyword
      if (role) params.role = role
      const res = await adminAPI.getUsers(params)
      setUsers(res.data.data)
      setTotal(res.data.pagination.total)
    } catch (err) {
      console.error('加载用户失败', err)
    }
  }

  const getRoleTag = (role: string) => {
    const roleMap: Record<string, { color: string; text: string }> = {
      buyer: { color: 'blue', text: '买家' },
      seller: { color: 'green', text: '商家' },
      admin: { color: 'gold', text: '管理员' },
    }
    const info = roleMap[role] || { color: 'default', text: role }
    return <Tag color={info.color}>{info.text}</Tag>
  }

  const getStatusTag = (status: string) => {
    const statusMap: Record<string, { color: string; text: string }> = {
      active: { color: 'green', text: '正常' },
      banned: { color: 'red', text: '已封禁' },
    }
    const info = statusMap[status] || { color: 'default', text: status }
    return <Tag color={info.color}>{info.text}</Tag>
  }

  // 后端暂未提供更新用户状态接口，功能已禁用
  // const handleBanUser = async (id: number, status: string) => {
  //   try {
  //     await adminAPI.updateUserStatus(id, { status })
  //     message.success(status === 'banned' ? '已封禁' : '已解封')
  //     loadUsers()
  //   } catch (err: any) {
  //     message.error(err.message || '操作失败')
  //   }
  // }

  const columns = [
    {
      title: 'ID',
      dataIndex: 'id',
      key: 'id',
      width: 80,
    },
    {
      title: '用户名',
      dataIndex: 'username',
      key: 'username',
    },
    {
      title: '昵称',
      dataIndex: 'nickname',
      key: 'nickname',
    },
    {
      title: '邮箱',
      dataIndex: 'email',
      key: 'email',
    },
    {
      title: '手机号',
      dataIndex: 'phone',
      key: 'phone',
    },
    {
      title: '角色',
      dataIndex: 'role',
      key: 'role',
      render: (role: string) => getRoleTag(role),
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      render: (status: string) => getStatusTag(status),
    },
    {
      title: '注册时间',
      dataIndex: 'createdAt',
      key: 'createdAt',
    },
    // 后端暂未提供更新用户状态接口，操作列已禁用
    // {
    //   title: '操作',
    //   key: 'action',
    //   width: 150,
    //   render: (_: any, record: User) => (
    //     <Space>
    //       {record.status === 'active' ? (
    //         <Button
    //           danger
    //           size="small"
    //           onClick={() => handleBanUser(record.id, 'banned')}
    //         >
    //           封禁
    //         </Button>
    //       ) : (
    //         <Button
    //           type="primary"
    //           size="small"
    //           onClick={() => handleBanUser(record.id, 'active')}
    //         >
    //           解封
    //         </Button>
    //       )}
    //     </Space>
    //   ),
    // },
  ]

  return (
    <div>
      <Title level={3}>用户管理</Title>

      <Card>
        <div style={{ display: 'flex', gap: 16, marginBottom: 16 }}>
          <Input.Search
            placeholder="搜索用户名/昵称..."
            value={keyword}
            onChange={(e) => setKeyword(e.target.value)}
            onSearch={() => setPage(1)}
            style={{ width: 300 }}
            allowClear
          />
          <Select
            placeholder="选择角色"
            allowClear
            style={{ width: 150 }}
            value={role}
            onChange={(val) => { setRole(val); setPage(1) }}
          >
            <Option value="buyer">买家</Option>
            <Option value="seller">商家</Option>
            <Option value="admin">管理员</Option>
          </Select>
        </div>

        <Table
          columns={columns}
          dataSource={users}
          rowKey="id"
          pagination={false}
        />

        <div style={{ textAlign: 'center', marginTop: 24 }}>
          <Pagination
            current={page}
            pageSize={pageSize}
            total={total}
            onChange={setPage}
          />
        </div>
      </Card>
    </div>
  )
}

export default AdminUsers
